//! Build-time SRI codegen for the public CSS modules.
//!
//! For every `.css` file in `public/css/`, we emit an entry in a
//! generated `css_sri.rs` of the form:
//!     ("tokens.css", "sha384-…")
//! The order matches `CSS_LOAD_ORDER` below — dependency order from
//! tokens through responsive, so the rendered `<link>` tags cascade
//! correctly. Build script reruns when any CSS file or this script
//! changes; no other file in the worker carries CSS bytes.

use std::env;
use std::fs;
use std::path::PathBuf;

use base64::Engine;
use sha2::{Digest, Sha384};

// Load order for the link-tag emission. Tokens first so cascading
// custom properties resolve in every following module; responsive
// last so its mobile overrides take precedence.
const CSS_LOAD_ORDER: &[&str] = &[
    "tokens.css",
    "reset.css",
    "buttons.css",
    "forms.css",
    "layout.css",
    "components.css",
    "responsive.css",
];

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let css_dir = manifest_dir.join("public").join("css");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    println!("cargo:rerun-if-changed=build.rs");

    let mut entries = String::new();
    for name in CSS_LOAD_ORDER {
        let path = css_dir.join(name);
        println!("cargo:rerun-if-changed={}", path.display());
        let bytes = fs::read(&path)
            .unwrap_or_else(|e| panic!("build.rs: failed to read {}: {e}", path.display()));
        let digest = Sha384::digest(&bytes);
        let b64 = base64::engine::general_purpose::STANDARD.encode(digest);
        entries.push_str(&format!("    (\"{name}\", \"sha384-{b64}\"),\n"));
    }

    let generated = format!(
        "// @generated by build.rs — do not edit\n\
         pub const CSS_MODULES: &[(&str, &str)] = &[\n{entries}];\n",
    );
    fs::write(out_dir.join("css_sri.rs"), generated).expect("write css_sri.rs");
}
