//! `GET /demo/personas`: JSON list of Approved-only personas from the
//! D1 catalog, populated into the welcome page's chat picker on first
//! open. Each row carries a sample business (name, type, city, hours,
//! goal) generated by the LLM under the operator's configurable
//! generation prompt, so the UI can render a "you're chatting as a
//! customer of …" card under the picker.
//!
//! Storage: the rolled-out personas live durably in KV under
//! `management:demo_personas:v1` (see `storage::StoredDemoPersonas`).
//! The cron tick refreshes the blob on the operator-configured cadence
//! (`DemoConfig::regeneration_cadence_mins`); a missing or empty store
//! triggers an inline regeneration on the request path so a brand-new
//! deploy still serves a populated picker on the first hit.

use serde::{Deserialize, Serialize};
use worker::*;

use crate::storage::{self, StoredDemoPersonas};

#[derive(Serialize, Deserialize, Clone, Default)]
pub struct DemoBusiness {
    #[serde(default)]
    pub name: String,
    #[serde(default)]
    pub business_type: String,
    #[serde(default)]
    pub city: String,
    #[serde(default)]
    pub hours: String,
    #[serde(default)]
    pub goal: String,
    #[serde(default)]
    pub goal_url: String,
}

#[derive(Serialize, Deserialize, Clone)]
pub struct DemoPersonaPayload {
    pub slug: String,
    pub label: String,
    pub description: String,
    pub greeting: String,
    /// The exact middle (frame + persona prompt) sent to the model on
    /// `/demo/chat`. Rendered in the "View system prompt" panel.
    pub prompt: String,
    pub business: DemoBusiness,
}

#[derive(Serialize, Deserialize, Clone, Default)]
pub struct DemoPersonasResponse {
    pub personas: Vec<DemoPersonaPayload>,
}

pub async fn handle_demo_personas(_req: Request, env: Env) -> Result<Response> {
    let kv = env.kv("KV")?;
    let db = env.d1("DB")?;

    // Demo gate. When the operator has flipped the toggle off, return
    // an empty list so the picker shows nothing and the welcome page's
    // chat factory has nothing to render.
    let demo_cfg = storage::get_demo_config(&kv).await.unwrap_or_default();
    if !demo_cfg.enabled {
        return json_response(&DemoPersonasResponse::default());
    }

    // Fast path: the cron tick keeps the stored blob fresh, so most
    // requests serve straight from KV without hitting D1 or the model.
    if let Ok(Some(stored)) = storage::get_stored_demo_personas(&kv).await {
        if let Ok(response) = serde_json::from_value::<DemoPersonasResponse>(stored.response) {
            if !response.personas.is_empty() {
                return json_response(&response);
            }
        }
    }

    // Cold start / post-archetype-edit miss. Generate inline so the
    // first visitor on a fresh deploy doesn't stare at an empty
    // picker, and persist so subsequent visitors hit the fast path.
    match regenerate_and_store(&env, &kv, &db, &demo_cfg.persona_generation_prompt).await {
        Ok(response) => json_response(&response),
        Err(msg) => {
            console_log!("demo personas: inline regen failed: {msg}");
            json_response(&DemoPersonasResponse::default())
        }
    }
}

/// Run the generator against the current Approved archetypes and write
/// the resulting blob into KV. Used by both the inline cold-miss path
/// here and the `/manage/demo/reroll` operator action and the cron
/// tick.
pub async fn regenerate_and_store(
    env: &Env,
    kv: &kv::KvStore,
    db: &D1Database,
    system_prompt: &str,
) -> std::result::Result<DemoPersonasResponse, String> {
    let archetypes = storage::list_archetypes(db, true)
        .await
        .map_err(|e| format!("D1 list_archetypes failed: {e:?}"))?;
    if archetypes.is_empty() {
        return Err("no Approved archetypes available".to_string());
    }

    let businesses = generate_demo_businesses(env, system_prompt, &archetypes).await?;
    let response = build_response(&archetypes, businesses);
    if response.personas.is_empty() {
        return Err("generator returned no parseable personas".to_string());
    }

    let stored = StoredDemoPersonas {
        generated_at: crate::helpers::now_iso(),
        response: serde_json::to_value(&response)
            .map_err(|e| format!("serialize stored personas: {e}"))?,
    };
    storage::save_stored_demo_personas(kv, &stored)
        .await
        .map_err(|e| format!("KV write failed: {e:?}"))?;
    console_log!(
        "demo personas: rolled {} businesses for {} archetypes",
        response.personas.len(),
        archetypes.len()
    );
    Ok(response)
}

/// Pair the generated businesses with the source archetypes (same
/// order) and produce the welcome-page response payload.
pub fn build_response(
    archetypes: &[crate::types::Archetype],
    businesses: Vec<DemoBusiness>,
) -> DemoPersonasResponse {
    let mut personas = Vec::with_capacity(archetypes.len());
    for (i, biz) in businesses.into_iter().enumerate() {
        if let Some(a) = archetypes.get(i) {
            let builder = crate::types::PersonaBuilder {
                archetype_slug: a.slug.clone(),
                biz_name: biz.name.clone(),
                biz_type: biz.business_type.clone(),
                city: biz.city.clone(),
                hours: biz.hours.clone(),
                goal: biz.goal.clone(),
                goal_url: biz.goal_url.clone(),
                ..Default::default()
            };
            let persona_middle = crate::personas::generate(&builder, &a.voice_prompt);
            personas.push(DemoPersonaPayload {
                slug: a.slug.clone(),
                label: a.label.clone(),
                description: a.description.clone(),
                greeting: a.greeting.clone(),
                prompt: crate::prompt::compose_demo_middle(&persona_middle),
                business: biz,
            });
        }
    }
    DemoPersonasResponse { personas }
}

/// Run the operator's generation prompt against the given archetypes
/// and return the parsed sample businesses. Shared by the public demo
/// list, the `/manage/demo/preview` endpoint, and the cron regen.
pub async fn generate_demo_businesses(
    env: &Env,
    system_prompt: &str,
    archetypes: &[crate::types::Archetype],
) -> std::result::Result<Vec<DemoBusiness>, String> {
    let user_prompt = archetypes
        .iter()
        .map(|a| format!("- {} ({})", a.label, a.description))
        .collect::<Vec<_>>()
        .join("\n");

    // Generous cap: ~512 tokens per archetype × default 4 ≈ 2048,
    // doubled for headroom on richer prompts and longer business
    // descriptions. Without this the model truncates mid-string after
    // the third entry.
    let reply = crate::ai::generate_persona_businesses(env, system_prompt, &user_prompt, 4096)
        .await
        .map_err(|e| format!("AI call failed: {e:?}"))?;

    // Strip an optional ```json fence the model sometimes adds.
    let clean = reply
        .trim()
        .trim_start_matches("```json")
        .trim_start_matches("```")
        .trim_end_matches("```")
        .trim();

    serde_json::from_str::<Vec<DemoBusiness>>(clean)
        .map_err(|e| format!("Could not parse JSON array: {e}. Raw reply: {reply}"))
}

fn json_response(data: &DemoPersonasResponse) -> Result<Response> {
    let body = serde_json::to_string(data)?;
    let headers = Headers::new();
    headers.set("Content-Type", "application/json")?;
    headers.set("Cache-Control", "no-store")?;
    Ok(Response::ok(body)?.with_headers(headers))
}
