//! Demo persona catalog resolution. The welcome page embeds the rolled
//! list inline in a `<script id="demo-personas-data">` block — the
//! client never fetches it. Each row carries a sample business (name,
//! type, city, hours, goal) generated by the LLM under the operator's
//! configurable generation prompt, so the UI can render a "you're
//! chatting as a customer of …" card under the picker.
//!
//! Storage: the rolled-out personas live durably in KV under
//! `management:demo_personas:v1` (see `storage::StoredDemoPersonas`).
//! The cron tick refreshes the blob on the operator-configured cadence
//! (`DemoConfig::regeneration_cadence_mins`); a missing or empty store
//! triggers an inline regeneration on the welcome request so a
//! brand-new deploy still serves a populated picker on the first hit.

use serde::{Deserialize, Serialize};
use worker::*;

use crate::storage::{self, StoredDemoPersonas};

#[derive(Serialize, Deserialize, Clone, Default)]
pub struct DemoBusiness {
    #[serde(default)]
    pub name: String,
    #[serde(default)]
    pub business_type: String,
    #[serde(default)]
    pub city: String,
    #[serde(default)]
    pub hours: String,
    #[serde(default)]
    pub goal: String,
    #[serde(default)]
    pub goal_url: String,
}

#[derive(Serialize, Deserialize, Clone)]
pub struct DemoPersonaPayload {
    pub slug: String,
    pub label: String,
    pub description: String,
    pub greeting: String,
    /// The exact middle (frame + persona prompt) sent to the model on
    /// `/demo/chat`. Rendered in the "View system prompt" panel.
    pub prompt: String,
    pub business: DemoBusiness,
}

#[derive(Serialize, Deserialize, Clone, Default)]
pub struct DemoPersonasResponse {
    pub personas: Vec<DemoPersonaPayload>,
}

/// Resolve the persona catalog the welcome page should embed. Returns
/// the JSON string ready to drop inside `<script id="demo-personas-data"
/// type="application/json">…</script>`.
///
/// The fallback ladder mirrors the previous `GET /demo/personas`
/// behaviour, just funnelled through the welcome handler instead of an
/// extra round-trip:
///   1. Fast path: cached blob in KV (kept warm by the cron tick).
///   2. Cold-start fallback: regenerate inline against D1 archetypes +
///      the LLM, then persist so subsequent visitors hit (1).
///   3. Anything still failing falls back to an empty `{personas:[]}`
///      payload — the page renders, the picker shows the operator-side
///      "no personas available" message, and we keep the welcome route
///      cheap (one KV read, no panics).
pub async fn resolve_personas_json(env: &Env) -> String {
    let empty = || {
        serde_json::to_string(&DemoPersonasResponse::default())
            .unwrap_or_else(|_| "{\"personas\":[]}".to_string())
    };

    let Ok(kv) = env.kv("KV") else { return empty() };
    let demo_cfg = storage::get_demo_config(&kv).await.unwrap_or_default();
    if !demo_cfg.enabled {
        return empty();
    }

    if let Ok(Some(stored)) = storage::get_stored_demo_personas(&kv).await {
        if let Ok(response) = serde_json::from_value::<DemoPersonasResponse>(stored.response) {
            if !response.personas.is_empty() {
                if let Ok(s) = serde_json::to_string(&response) {
                    return s;
                }
            }
        }
    }

    let Ok(db) = env.d1("DB") else { return empty() };
    match regenerate_and_store(env, &kv, &db, &demo_cfg.persona_generation_prompt).await {
        Ok(response) => serde_json::to_string(&response).unwrap_or_else(|_| empty()),
        Err(msg) => {
            console_log!("demo personas: inline regen failed: {msg}");
            empty()
        }
    }
}

/// Run the generator against the current Approved archetypes and write
/// the resulting blob into KV. Used by both the inline cold-miss path
/// here and the `/manage/demo/reroll` operator action and the cron
/// tick.
pub async fn regenerate_and_store(
    env: &Env,
    kv: &kv::KvStore,
    db: &D1Database,
    system_prompt: &str,
) -> std::result::Result<DemoPersonasResponse, String> {
    let archetypes = storage::list_archetypes(db, true)
        .await
        .map_err(|e| format!("D1 list_archetypes failed: {e:?}"))?;
    if archetypes.is_empty() {
        return Err("no Approved archetypes available".to_string());
    }

    let businesses = generate_demo_businesses(env, system_prompt, &archetypes).await?;
    let response = build_response(&archetypes, businesses);
    if response.personas.is_empty() {
        return Err("generator returned no parseable personas".to_string());
    }

    let stored = StoredDemoPersonas {
        generated_at: crate::helpers::now_iso(),
        response: serde_json::to_value(&response)
            .map_err(|e| format!("serialize stored personas: {e}"))?,
    };
    storage::save_stored_demo_personas(kv, &stored)
        .await
        .map_err(|e| format!("KV write failed: {e:?}"))?;
    console_log!(
        "demo personas: rolled {} businesses for {} archetypes",
        response.personas.len(),
        archetypes.len()
    );
    Ok(response)
}

/// Pair the generated businesses with the source archetypes (same
/// order) and produce the welcome-page response payload.
pub fn build_response(
    archetypes: &[crate::types::Archetype],
    businesses: Vec<DemoBusiness>,
) -> DemoPersonasResponse {
    let mut personas = Vec::with_capacity(archetypes.len());
    for (i, biz) in businesses.into_iter().enumerate() {
        if let Some(a) = archetypes.get(i) {
            let builder = crate::types::PersonaBuilder {
                archetype_slug: a.slug.clone(),
                biz_name: biz.name.clone(),
                biz_type: biz.business_type.clone(),
                city: biz.city.clone(),
                hours: biz.hours.clone(),
                goal: biz.goal.clone(),
                goal_url: biz.goal_url.clone(),
                ..Default::default()
            };
            let persona_middle = crate::personas::generate(&builder, &a.voice_prompt);
            personas.push(DemoPersonaPayload {
                slug: a.slug.clone(),
                label: a.label.clone(),
                description: a.description.clone(),
                greeting: a.greeting.clone(),
                prompt: crate::prompt::compose_demo_middle(&persona_middle),
                business: biz,
            });
        }
    }
    DemoPersonasResponse { personas }
}

/// Run the operator's generation prompt against the given archetypes
/// and return the parsed sample businesses. Shared by the public demo
/// list, the `/manage/demo/preview` endpoint, and the cron regen.
pub async fn generate_demo_businesses(
    env: &Env,
    system_prompt: &str,
    archetypes: &[crate::types::Archetype],
) -> std::result::Result<Vec<DemoBusiness>, String> {
    let user_prompt = archetypes
        .iter()
        .map(|a| format!("- {} ({})", a.label, a.description))
        .collect::<Vec<_>>()
        .join("\n");

    // Generous cap: ~512 tokens per archetype × default 4 ≈ 2048,
    // doubled for headroom on richer prompts and longer business
    // descriptions. Without this the model truncates mid-string after
    // the third entry.
    let reply = crate::ai::generate_persona_businesses(env, system_prompt, &user_prompt, 4096)
        .await
        .map_err(|e| format!("AI call failed: {e:?}"))?;

    // Strip an optional ```json fence the model sometimes adds.
    let clean = reply
        .trim()
        .trim_start_matches("```json")
        .trim_start_matches("```")
        .trim_end_matches("```")
        .trim();

    let mut parsed: Vec<DemoBusiness> = serde_json::from_str(clean)
        .map_err(|e| format!("Could not parse JSON array: {e}. Raw reply: {reply}"))?;
    // Defensive rewrite: every goal_url must point at example.com so a
    // model that drifts from the prompt (or an operator who edits the
    // instructions) can't sneak a real-looking domain into the demo.
    for biz in &mut parsed {
        biz.goal_url = sanitize_demo_goal_url(&biz.goal_url);
    }
    Ok(parsed)
}

/// Coerce a model-supplied goal_url into something rooted at
/// `https://example.com`. Empty input passes through (the UI then
/// hides the link). Anything else gets its host swapped — paths,
/// queries, and fragments are preserved so the goal copy stays
/// recognizable. Bare paths and unknown schemes are also normalized.
pub(crate) fn sanitize_demo_goal_url(raw: &str) -> String {
    let trimmed = raw.trim();
    if trimmed.is_empty() {
        return String::new();
    }

    let rest = trimmed
        .strip_prefix("https://")
        .or_else(|| trimmed.strip_prefix("http://"));
    let path_segment = match rest {
        // Has a scheme: pull out the path-and-after, drop the host.
        Some(after_scheme) => match after_scheme.find('/') {
            Some(i) => {
                let host = &after_scheme[..i];
                let path = &after_scheme[i..];
                let host_lower = host.to_lowercase();
                if host_lower == "example.com" || host_lower.ends_with(".example.com") {
                    return format!("https://{host}{path}");
                }
                path.to_string()
            }
            None => {
                // No path component at all (e.g. https://acme.com).
                // example.com root stays canonical; other hosts collapse
                // to a bare example.com root too.
                let host_lower = after_scheme.to_lowercase();
                if host_lower == "example.com" || host_lower.ends_with(".example.com") {
                    return format!("https://{after_scheme}");
                }
                "/".to_string()
            }
        },
        // No scheme: treat as a relative path or naked domain. Either
        // way we ignore the input host (if any) and prepend a slash.
        None => {
            if trimmed.starts_with('/') {
                trimmed.to_string()
            } else {
                format!("/{trimmed}")
            }
        }
    };

    format!("https://example.com{path_segment}")
}

#[cfg(test)]
mod tests {
    use super::sanitize_demo_goal_url as s;

    #[test]
    fn empty_passes_through() {
        assert_eq!(s(""), "");
        assert_eq!(s("   "), "");
    }

    #[test]
    fn example_com_is_preserved() {
        assert_eq!(s("https://example.com/book"), "https://example.com/book");
        assert_eq!(s("https://example.com"), "https://example.com");
        assert_eq!(s("https://www.example.com/x"), "https://www.example.com/x");
    }

    #[test]
    fn other_hosts_get_rewritten_keeping_path() {
        assert_eq!(
            s("https://acme.bakery.com/order"),
            "https://example.com/order"
        );
        assert_eq!(
            s("http://shop.example.org/items?id=1#a"),
            "https://example.com/items?id=1#a"
        );
    }

    #[test]
    fn other_hosts_with_no_path_collapse_to_root() {
        assert_eq!(s("https://acme.com"), "https://example.com/");
    }

    #[test]
    fn relative_paths_get_a_host() {
        assert_eq!(s("/book"), "https://example.com/book");
        assert_eq!(s("book"), "https://example.com/book");
    }

    #[test]
    fn http_scheme_is_normalized_to_https() {
        assert_eq!(s("http://example.com/x"), "https://example.com/x");
    }
}
