//! The HTML document every app route is served from.
//!
//! Routes the Elm app owns but which aren't prerendered — `/wizard`,
//! `/dashboard/*`, `/manage` — get this from the Worker. The marketing routes
//! get a prerendered file of the same shape straight off Cloudflare's asset
//! handler, without the Worker running at all; see `tests/prerender.spec.ts`.
//!
//! Both come from [`html`], so the two can't drift: the prerenderer boots the
//! app against *this* shell and snapshots the result.
//!
//! The page carries no copy. Every string the user reads lives in the Elm app,
//! because a second copy here would be the one that goes stale. There is no
//! mount `<div>` either: this is a `Browser.application`, which takes over
//! `<body>` and removes whatever it finds there.
//!
//! That last point is why the two `<script>` tags are in `<head>` with `defer`
//! rather than at the end of `<body>`, where they would more conventionally
//! go. Elm removes the body's children on init, scripts included — harmless
//! for a Worker-rendered page, but the prerenderer snapshots the DOM *after*
//! that happens, so a body-tagged script would be missing from the static
//! files and they would load as inert HTML with dead navigation. `defer`
//! keeps the execution order (bundle, then initialiser) and waits for the
//! document, which `Browser.application` needs.
//!
//! There is deliberately no inline script. The prerendered files are static, so
//! nothing can stamp a per-response nonce into them, and a policy that has to
//! admit inline script on some pages is weaker everywhere. `/boot.js` does the
//! initialisation instead, which lets every route — static or not — run under
//! `script-src 'self'`.

/// The stylesheets, in cascade order.
///
/// Tokens first so the custom properties every other file reads are defined;
/// `responsive` last so its media-query overrides win. A name here without a
/// matching file in `public/css/` gives a 404, which `tests/app.spec.ts`
/// catches by asserting each one loads.
///
/// These used to carry Subresource Integrity hashes generated by a `build.rs`.
/// That was removed rather than extended, for two reasons. It defended nothing:
/// the files are same-origin, so anyone able to modify them could equally
/// modify `/app.js`, which never carried a hash — the measure was applied to
/// the stylesheets but not to the executable code. And it failed silently in a
/// way prerendering made worse: the hashes were baked into the wasm at compile
/// time while the static pages embedding them are generated separately, so a
/// CSS edit without regenerating both blocks a stylesheet on the public
/// marketing pages, with the page still rendering and nothing reported.
const STYLESHEETS: &[&str] = &[
    "tokens.css",
    "reset.css",
    "buttons.css",
    "forms.css",
    "layout.css",
    "components.css",
    "responsive.css",
];

/// Render the shell.
///
/// The title and description are the generic site-wide values; the Elm app
/// rewrites both on navigation, and the prerenderer captures whatever the app
/// set for the route it was snapshotting.
pub fn html() -> String {
    let stylesheets: String = STYLESHEETS
        .iter()
        .map(|name| format!("<link rel=\"stylesheet\" href=\"/css/{name}\">\n"))
        .collect();

    format!(
        r#"<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Concierge</title>
<meta name="description" content="Automated customer messaging for small businesses. Auto-reply on WhatsApp, with a human picking up when it matters.">
<link rel="icon" href="/favicon-32.png" sizes="32x32">
<link rel="icon" href="/favicon-16.png" sizes="16x16">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
<link rel="manifest" href="/site.webmanifest">
{stylesheets}<script defer src="/app.js"></script>
<script defer src="/boot.js"></script>
</head>
<body>
</body>
</html>
"#,
        stylesheets = stylesheets
    )
}
