//! The single HTML document the whole app is served from.
//!
//! Every route that isn't the API, a webhook, an OAuth callback or a static
//! asset gets this page, and the Elm app in `frontend/` takes over from
//! there. The Worker owns the shell rather than shipping a `public/index.html`
//! asset so there is exactly one code path that produces it, and so the CSP
//! nonce can be stamped in per response.
//!
//! The page is deliberately almost empty. It carries no copy, because every
//! string the user reads lives in the Elm app — putting any of it here would
//! mean two places to change it, and the one here would be the stale one.
//!
//! **This is not server-side rendered.** A crawler that doesn't run
//! JavaScript sees `<div id="app">` and nothing else, so the marketing routes
//! (`/`, `/pricing`, `/features`) are currently invisible to them. That was a
//! deliberate trade for shipping speed; the fix is a build-time prerender of
//! those routes into static assets, which does not change the Elm app.

// Generated by build.rs: `[(filename, "sha384-…")]` in cascade order,
// tokens first so custom properties resolve, responsive last so its mobile
// overrides win.
include!(concat!(env!("OUT_DIR"), "/css_sri.rs"));

/// Placeholder the shell emits where a CSP nonce belongs. The fetch wrapper
/// swaps it for a per-response random value and writes the matching header.
pub const CSP_NONCE_PLACEHOLDER: &str = "__CSP_NONCE__";

/// Render the shell.
///
/// The title and description are the generic site-wide values; the Elm app
/// rewrites both on navigation. They exist so a link shared before the app
/// boots still says something sane.
pub fn html() -> String {
    let stylesheets: String = CSS_MODULES
        .iter()
        .map(|(name, sri)| {
            format!(
                "<link rel=\"stylesheet\" href=\"/css/{name}\" integrity=\"{sri}\" crossorigin=\"anonymous\">\n"
            )
        })
        .collect();

    format!(
        r#"<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Concierge</title>
<meta name="description" content="Automated customer messaging for small businesses. Auto-reply on WhatsApp, with a human picking up when it matters.">
<link rel="icon" href="/favicon-32.png" sizes="32x32">
<link rel="icon" href="/favicon-16.png" sizes="16x16">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
<link rel="manifest" href="/site.webmanifest">
{stylesheets}</head>
<body>
<div id="app"></div>
<script nonce="{nonce}" src="/app.js"></script>
<script nonce="{nonce}">
  // Elm.Main.init is the only entry point. Flags carry what the app cannot
  // discover for itself: the viewport width, so the first render isn't a
  // desktop layout that immediately reflows on a phone. Everything else
  // comes from GET /api/bootstrap.
  Elm.Main.init({{
    node: document.getElementById('app'),
    flags: {{ width: window.innerWidth }}
  }});
</script>
</body>
</html>
"#,
        stylesheets = stylesheets,
        nonce = CSP_NONCE_PLACEHOLDER
    )
}
