//! The HTML document every app route is served from.
//!
//! Routes the Elm app owns but which aren't prerendered — `/wizard`,
//! `/dashboard/*`, `/manage` — get this from the Worker. The marketing routes
//! get a prerendered file of the same shape straight off Cloudflare's asset
//! handler, without the Worker running at all; see `tests/prerender.spec.ts`.
//!
//! Both come from [`html`], so the two can't drift: the prerenderer boots the
//! app against *this* shell and snapshots the result.
//!
//! The page carries no copy. Every string the user reads lives in the Elm app,
//! because a second copy here would be the one that goes stale. There is no
//! mount `<div>` either: this is a `Browser.application`, which takes over
//! `<body>` and removes whatever it finds there.
//!
//! That last point is why the two `<script>` tags are in `<head>` with `defer`
//! rather than at the end of `<body>`, where they would more conventionally
//! go. Elm removes the body's children on init, scripts included — harmless
//! for a Worker-rendered page, but the prerenderer snapshots the DOM *after*
//! that happens, so a body-tagged script would be missing from the static
//! files and they would load as inert HTML with dead navigation. `defer`
//! keeps the execution order (bundle, then initialiser) and waits for the
//! document, which `Browser.application` needs.
//!
//! There is deliberately no inline script. The prerendered files are static, so
//! nothing can stamp a per-response nonce into them, and a policy that has to
//! admit inline script on some pages is weaker everywhere. `/boot.js` does the
//! initialisation instead, which lets every route — static or not — run under
//! `script-src 'self'`.
//!
//! # Subresource Integrity
//!
//! Every stylesheet and both scripts carry an `integrity` hash generated at
//! build time by `build.rs`. An SRI rejection is *silent* — the page still
//! renders, the asset simply never applies — so the ordering that keeps the
//! hashes correct is enforced rather than merely documented:
//!
//! * `scripts/build-worker.sh` builds the frontend before the wasm, so
//!   `build.rs` hashes the `app.js` that will actually be served.
//! * `build.rs` refuses to emit a placeholder for a file it cannot read, so a
//!   crate compiled without the frontend fails loudly rather than producing
//!   hashes that would block the bundle at runtime.
//! * The prerendered pages inherit these hashes by snapshotting this shell, and
//!   CI regenerates them and fails on a diff — so a frontend rebuild without a
//!   re-prerender can't leave stale hashes in the static files.
//! * `tests/app.spec.ts` asserts every stylesheet is *applied* and that the app
//!   actually boots, which is exactly what a blocked asset would break.

// Generated by build.rs: `CSS_MODULES` and `SCRIPTS`, each
// `[(file, "sha384-…")]` in load order.
include!(concat!(env!("OUT_DIR"), "/asset_sri.rs"));

/// Render the shell.
///
/// The title and description are the generic site-wide values; the Elm app
/// rewrites both on navigation, and the prerenderer captures whatever the app
/// set for the route it was snapshotting.
pub fn html() -> String {
    let stylesheets: String = CSS_MODULES
        .iter()
        .map(|(name, sri)| {
            format!(
                "<link rel=\"stylesheet\" href=\"/css/{name}\" integrity=\"{sri}\" crossorigin=\"anonymous\">\n"
            )
        })
        .collect();

    let scripts: String = SCRIPTS
        .iter()
        .map(|(name, sri)| {
            format!(
                "<script defer src=\"/{name}\" integrity=\"{sri}\" crossorigin=\"anonymous\"></script>\n"
            )
        })
        .collect();

    format!(
        r#"<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Concierge</title>
<meta name="description" content="Automated customer messaging for small businesses. Auto-reply on WhatsApp, with a human picking up when it matters.">
<link rel="icon" href="/favicon-32.png" sizes="32x32">
<link rel="icon" href="/favicon-16.png" sizes="16x16">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
<link rel="manifest" href="/site.webmanifest">
{stylesheets}{scripts}</head>
<body>
</body>
</html>
"#,
        stylesheets = stylesheets,
        scripts = scripts
    )
}
